### ISSUE TITLE
[승하차 알람] 화면 띄워질 때 시점문제로 앱이 죽는 현상

### ISSUE THREAD

**Issue by Modyhoon** [boostcampwm-2021/iOS09-BBus#185]
## 발생 일시
11/17 17:40분경

## 발생 위치
승하차 알람 설정 화면

## 증상
앱이 죽어버림

## 재현 방법
모름. 그냥 심심할때나옴 잊혀질만하면
## 스크린샷
![image](https://user-images.githubusercontent.com/72058473/142178970-631f0295-1d1b-4a9f-ab27-239fde75e85f.png)

## 레퍼런스
없음.

**Comment by sujeong000** [comment]
`reloadSection()` 에서 row개수 안맞아서 터지는 것 같음.

**Comment by sujeong000** [comment]
현재는 `reloadSection()`이 아니라 `reload()`로 전체 리로드를 하고 있기 때문에 문제가 발생하지 않을 것으로 예상함.
