### ISSUE TITLE
[정거장 정보] 각 셀에 걸려있는 알람버튼 관련 sink에서 발생하는  index out of range에러

### ISSUE THREAD

**Issue by sujeong000** [boostcampwm-2021/iOS09-BBus#266]
## 발생 일시
2021.11.24(수)

## 발생 위치
정거장 화면

## 증상
가끔 각 cell에 걸려 있는 sink 부분에서 index out of range 에러가 발생
새 정보를 받아오면서 info 버스가 no info버스가 되거나 하면서 버스 개수가 달라진 것 같음

## 재현 방법
새로고침하여 reload를 계속 호출하다보면 발생

## 스크린샷
![스크린샷 2021-11-24 오후 3 53 29](https://user-images.githubusercontent.com/70833900/143189870-f9b4cd2f-7271-467e-a758-3d2f605b5d7c.png)

## 레퍼런스
없음.

**Comment by Modyhoon** [comment]
이 이슈는 #263  에서 다룹니다. close하겠습니다.
